repos:
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    language: system
- repo: local
  hooks:
  - id: prospector
    name: prospector
    entry: prospector
    types: [file, python]
    language: system
    exclude: '^(doc/)|(examples/)|(futures/)'
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
  hooks:
  -   id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v4.3.21'
  hooks:
  - id: isort
