language: python
python:
  - "3.6"
  - "3.7"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - rabbitmq-server
before_install:
  - sudo service postgresql restart
install:
  - pip install -U 'pip<19' wheel setuptools
  - pip install .[dev]
  - reentry scan
env:
  - TEST_TYPE="tests"
  - TEST_TYPE="pre-commit"
script:
  - ./.travis-data/test_script.sh
