language: python
python:
  - "2.7"
  - "3.6"
cache: pip
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "9.5"
install:
  - pip install -U 'pip<19' wheel setuptools
  - pip install git+https://github.com/aiidateam/aiida_core@v1.0.0a4#egg=aiida_core
  - pip install git+https://github.com/greschd/aiida_pytest@support_alpha_4#egg=aiida_pytest
  - pip install .[dev]
env:
  - TEST_TYPE="tests"
  - TEST_TYPE="pre-commit"
script:
  - ./.travis-data/test_script.sh
