language: python
python: 2.7
cache: pip
sudo: true
services:
  - postgresql
addons:
  postgresql: "9.5"
before_install:  # copied from pgtest's travis.yml
  - sudo apt-get install locate
  - sudo service postgresql stop
  - sudo apt-get remove postgresql
  - sudo apt-get install postgresql
  - sudo updatedb
install:
  - pip install -U pip wheel setuptools
  # Unreleased plum version required for fast-forwarding
  - pip install git+https://github.com/greschd/plumpy@submit_with_process_type
  - pip install git+https://github.com/greschd/aiida_core@edge_new#egg=aiida_core
  - pip install git+https://github.com/greschd/aiida-tools#egg=aiida_tools
  - pip install git+https://github.com/greschd/aiida_pytest#egg=aiida_pytest
  - pip install .[dev]
env:
  - TEST_TYPE="tests"
  - TEST_TYPE="pre-commit"
script:
  - ./.travis-data/test_script.sh
