language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TEST_TYPE="pre-commit" INSTALL_TYPE="dev_precommit"
  - TEST_TYPE="tests" INSTALL_TYPE="testing"
  - TEST_TYPE="tests" INSTALL_TYPE="testing_sdist"
jobs:
  exclude:
  - python: "3.8"
    env: TEST_TYPE="pre-commit" INSTALL_TYPE="dev_precommit"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - rabbitmq-server
before_install:
  - sudo service postgresql restart
install:
  - ./.travis-data/install_script.sh
script:
  - ./.travis-data/test_script.sh
